// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interface.go -destination=internal/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	storage "github.com/wickedv43/go-goph-keeper/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockGophKeeper is a mock of GophKeeper interface.
type MockGophKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockGophKeeperMockRecorder
	isgomock struct{}
}

// MockGophKeeperMockRecorder is the mock recorder for MockGophKeeper.
type MockGophKeeperMockRecorder struct {
	mock *MockGophKeeper
}

// NewMockGophKeeper creates a new mock instance.
func NewMockGophKeeper(ctrl *gomock.Controller) *MockGophKeeper {
	mock := &MockGophKeeper{ctrl: ctrl}
	mock.recorder = &MockGophKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophKeeper) EXPECT() *MockGophKeeperMockRecorder {
	return m.recorder
}

// CreateVault mocks base method.
func (m *MockGophKeeper) CreateVault(ctx context.Context, v *storage.VaultRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVault", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVault indicates an expected call of CreateVault.
func (mr *MockGophKeeperMockRecorder) CreateVault(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVault", reflect.TypeOf((*MockGophKeeper)(nil).CreateVault), ctx, v)
}

// DeleteVault mocks base method.
func (m *MockGophKeeper) DeleteVault(ctx context.Context, vID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVault", ctx, vID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVault indicates an expected call of DeleteVault.
func (mr *MockGophKeeperMockRecorder) DeleteVault(ctx, vID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVault", reflect.TypeOf((*MockGophKeeper)(nil).DeleteVault), ctx, vID)
}

// GetVault mocks base method.
func (m *MockGophKeeper) GetVault(ctx context.Context, vID uint64) (storage.VaultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVault", ctx, vID)
	ret0, _ := ret[0].(storage.VaultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVault indicates an expected call of GetVault.
func (mr *MockGophKeeperMockRecorder) GetVault(ctx, vID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVault", reflect.TypeOf((*MockGophKeeper)(nil).GetVault), ctx, vID)
}

// ListVaults mocks base method.
func (m *MockGophKeeper) ListVaults(ctx context.Context, uID uint64) ([]storage.VaultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVaults", ctx, uID)
	ret0, _ := ret[0].([]storage.VaultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVaults indicates an expected call of ListVaults.
func (mr *MockGophKeeperMockRecorder) ListVaults(ctx, uID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVaults", reflect.TypeOf((*MockGophKeeper)(nil).ListVaults), ctx, uID)
}

// NewUser mocks base method.
func (m *MockGophKeeper) NewUser(ctx context.Context, u *storage.User) (storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUser", ctx, u)
	ret0, _ := ret[0].(storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUser indicates an expected call of NewUser.
func (mr *MockGophKeeperMockRecorder) NewUser(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUser", reflect.TypeOf((*MockGophKeeper)(nil).NewUser), ctx, u)
}

// UpdateVault mocks base method.
func (m *MockGophKeeper) UpdateVault(ctx context.Context, v *storage.VaultRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVault", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVault indicates an expected call of UpdateVault.
func (mr *MockGophKeeperMockRecorder) UpdateVault(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVault", reflect.TypeOf((*MockGophKeeper)(nil).UpdateVault), ctx, v)
}

// User mocks base method.
func (m *MockGophKeeper) User(ctx context.Context, id uint64) (storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, id)
	ret0, _ := ret[0].(storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockGophKeeperMockRecorder) User(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockGophKeeper)(nil).User), ctx, id)
}

// UserByLogin mocks base method.
func (m *MockGophKeeper) UserByLogin(ctx context.Context, login string) (storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByLogin", ctx, login)
	ret0, _ := ret[0].(storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByLogin indicates an expected call of UserByLogin.
func (mr *MockGophKeeperMockRecorder) UserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByLogin", reflect.TypeOf((*MockGophKeeper)(nil).UserByLogin), ctx, login)
}
