version: '3'

tasks:
  server:
    go run ./cmd/server/. -c=./config/config.local.yaml
  client:
    go run ./cmd/client/.


  protoc:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest


  protoc-create:
    protoc -I=proto/ --go_out=./internal/api/ --go_opt=paths=source_relative --go-grpc_out=./internal/api/ --go-grpc_opt=paths=source_relative proto/*.proto